spring:
  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.naver.com
            enable: 'true'
          starttls:
            enable: 'true'
          auth: 'true'
    username: jun1234755@naver.com
    port: '465'
    default-encoding: UTF-8
    host: smtp.naver.com
    password: junsang1!
  thymeleaf:
    cache: 'false'
    check-template: 'true'
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      maxRequestSize: 10MB
      maxFileSize: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: test123!@#
    username: poly
    url: jdbc:mysql://db-1s69o-kr1.vpc-cdb.gov-ntruss.com:3306/myDB
  profiles:
    active: prod
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: kopo.poly.dto
  configuration:
    map-underscore-to-camel-case: 'true'
cloud:
  aws:
    region:
      static: ap-northeast-2
server:
  port: '11001'